### ISSUE TITLE
Light falloff shouldn't be in BaseLight

### ISSUE THREAD

**Issue by ozxybox** [StrataSource/FGD#180]
The light falloff parameters only apply to `light` and `light_spot`, not `light_directional` or `light_environment`. Should we have a new base light for these two?

Falloff parameters:
```
_zero_percent_distance
_fifty_percent_distance
_hardfalloff
_constant_attn
_linear_attn
_quadratic_attn
_distance
```

**Comment by tmob03** [comment]
@ozxybox These key values are only on light and light_spot already, these two definitions inherit from BaseLight while light_directional and light_environment do not

**Comment by tmob03** [comment]
Ah, nevermind, I see the issue. light_directional has inputs and kvs from BaseLight that should be inherited, while  not having these keyvalues.

**Comment by TeamSpen210** [comment]
Actually, `BaseLight` is only used for `light`/`light_spot`, not the others.

**Comment by tmob03** [comment]
> Actually, `BaseLight` is only used for `light`/`light_spot`, not the others.

Yes, but it should 🙃, these two ents have all the inputs and kvs of BaseLight, minus the above.
